import type { Metadata } from "next";
import "./globals.css";

import NextAuthProvider from "@/cmp/NextAuthProvider";

export const metadata: Metadata = {
  title: "JavaScript道場",
  // description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // can get session info on server
  // const session = await getServerSession();

  return (
    <html lang="ja" className="scroll-smooth">
      <body>
        <NextAuthProvider>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
